icons_format = "{icon}"

[theme]
#theme = "ctp-macchiato"
theme = "nord-dark"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome4"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid |Wired connection}"

[[block]]
block = "battery"
format = "battery:$percentage {$time_remaining.dur(hms:true, min_unit:m) |}"
device = "BAT0"

[[block]]
block = "packages"

[[block]]
block = "uptime"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

