wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/joyboy.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = ~/Pictures/Wallpapers/joyboy.png
    fit_mode = cover
}
wallpaper {
    monitor = DP-5
    path = ~/Pictures/Wallpapers/joyboy.png
    fit_mode = cover
}
