[general]
import = ["~/.config/alacritty/rose-pine-moon.toml"]

[window]
decorations = "None"
opacity = 0.9

[font]
normal.family = "JetBrainsMono"
bold.family = "JetBrainsMono"
italic.family = "JetBrainsMono"
bold_italic.family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always"}

[terminal]
shell = "/bin/zsh"

[mouse]
hide_when_typing = true
