[general]
import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[window]
decorations = "Transparent"
startup_mode = "Maximized"
opacity = 0.9
decorations_theme_variant = "Dark"

[font.normal]
#family = "JetbrainsMono Nerd Font"

# [font.bold]
# family = "JetbrainsMono Nerd Font"
#
# [font.italic]
# family = "JetbrainsMono Nerd Font"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always"}

[terminal]
shell = "/bin/zsh"

[mouse]
hide_when_typing = true
