[general]
#import = ["~/.config/alacritty/themes/oxcarbon.toml"]
import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]

[window]
decorations = "Transparent"
startup_mode = "Maximized"
opacity = 0.9
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrainsMono"
bold.family = "JetBrainsMono"
italic.family = "JetBrainsMono"
bold_italic.family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always"}

[terminal]
shell = "/bin/zsh"

[mouse]
hide_when_typing = true
