set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'rose-pine/tmux'
#set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'vaaleyard/tmux-dotbar'


# set colorscheme back to rose pine
set -g @rose_pine_variant 'moon'
set -g @rose_pine_host 'on' # Enables hostname in the status bar
set -g @rose_pine_directory 'on' # Turn on the current folder component in the status bar
set -g @rose_pine_git 'on' # Turn on the git status component in the status bar
set -g @rose_pine_left_separator '  ' # The strings to use as separators are 1-space padded
set -g @rose_pine_right_separator '  ' # Accepts both normal chars & nerdfont icons
set -g @rose_pine_field_separator '  ' # Again, 1-space padding, it updates with prefix + I
set -g @rose_pine_bar_bg_disable 'on' # Disables background color, for transparent terminal emulators
set -g @rose_pine_hostname_short 'on' # Makes the hostname shorter by using tmux's '#h' format
set -g @rose_pine_date_time '' # It accepts the date UNIX command format (man date for info)
set -g @rose_pine_user 'on' # Turn on the username component in the statusbar

set -g default-command /bin/zsh
set-option -sg escape-time 10
# fix colors in terminal
# this is the command
#set -as terminal-overrides ",screen*:Tc"
#set-option -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-kitty:Tc"
#set -g default-terminal "tmux-256color"

# enable mouse support
set -g mouse on

# set windows to start at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# use vim mode keys to move around and do stuff
set -g mode-keys vi
# Change the regular expression used to detect vim. This pattern must be
# compatible with `grep -iE` extended regular expression syntax.
set -g @vim_navigator_pattern '(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'

# Override the shell script logic for detecting vim. Instances of
# '@vim_navigator_pattern' will automatically be substituted with your override
# of '@vim_navigator_pattern', or it will use the default @vim_navigator_pattern
# if you haven't overridden the option.
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +@vim_navigator_pattern$'"
set -g @vim_navigator_check "${is_vim}"

# set yank to copy to system clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# set default behavior to open tabs and splits in the same directory
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
